# Generated by Django 4.0 on 2021-12-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
