# Generated by Django 4.0 on 2021-12-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_image_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'permissions': [('can_publish', 'Can publish posts')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/%Y/%m', verbose_name='File')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Caption')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
                'ordering': ['post'],
            },
        ),
    ]
