# Generated by Django 4.0 on 2021-12-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_options_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'permissions': [('can_publish', 'Can publish Post')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
