# Generated by Django 4.0 on 2021-12-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'permissions': [('can_write', 'Can write Post'), ('can_publish', 'Can publish Post')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
