# Generated by Django 4.0 on 2021-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5, verbose_name='Side')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='Position')),
                ('callable_function', models.CharField(max_length=150, verbose_name='Function')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('errors', models.TextField(blank=True, verbose_name='Errors')),
            ],
        ),
    ]
