# Generated by Django 4.0 on 2021-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
