# Generated by Django 4.0 on 2021-12-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_extension_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'ordering': ['side', 'position'], 'verbose_name': 'Extension', 'verbose_name_plural': 'Extensions'},
        ),
    ]
