# Generated by Django 4.0 on 2021-12-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_extension_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extension',
            old_name='callable_function',
            new_name='callable',
        ),
    ]
