# Generated by Django 4.0 on 2021-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_callable_function_extension_callable'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='html_id',
            field=models.SlugField(default='id', verbose_name='HTML ID'),
            preserve_default=False,
        ),
    ]
