# Generated by Django 4.0 on 2021-12-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='Login required'),
        ),
    ]
