# Generated by Django 4.0 on 2022-01-01 08:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_extension_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='js_file',
            field=models.FileField(blank=True, upload_to=core.models.js_path, verbose_name='JS File'),
        ),
    ]
