# Generated by Django 4.0 on 2022-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_post_views_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('ident', models.SlugField(max_length=100, unique=True, verbose_name='Identifier')),
                ('raw', models.TextField(verbose_name='Raw content')),
                ('html', models.TextField(blank=True, editable=False)),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Show in menu')),
                ('fa_icon', models.CharField(blank=True, max_length=30, verbose_name='Font Awesome Icon')),
            ],
            options={
                'verbose_name': 'Site info',
                'verbose_name_plural': 'Site infos',
                'ordering': ['name'],
            },
        ),
    ]
