# Generated by Django 4.0 on 2022-01-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_siteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='fa_icon',
            field=models.CharField(default='fas fa-info', max_length=30, verbose_name='Font Awesome Icon'),
        ),
    ]
