# Generated by Django 4.0 on 2022-01-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_siteinfo_fa_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'ordering': ['name'], 'verbose_name': 'Site Info', 'verbose_name_plural': 'Site Infos'},
        ),
    ]
