# Generated by Django 4.0 on 2022-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='internal',
            field=models.BooleanField(default=False, verbose_name='Internal'),
        ),
    ]
