# Generated by Django 4.0 on 2022-01-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_post_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='internal',
        ),
    ]
